FROM balenalib/%%BALENA_MACHINE_NAME%%

RUN apt-get update && apt-get install -y \
git \
build-essential \
python-pip \
libglib2.0-dev \
bluez \
&& apt-get clean && rm -rf /var/lib/apt/lists/*
RUN pip install requests
